import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica'
  },
  header: {
    fontSize: 26,
    marginBottom: 10,
    textAlign: 'center',
    color: '#2563eb',
    fontWeight: 'bold'
  },
  subHeader: {
    fontSize: 12,
    marginBottom: 20,
    textAlign: 'center',
    color: '#64748b'
  },
  sectionTitle: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    color: '#1e293b',
    fontWeight: 'heavy',
    borderBottom: '1px solid #e2e8f0',
    paddingBottom: 5
  },
  itemContainer: {
    marginBottom: 8,
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 6
  },
  itemName: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4
  },
  itemDetails: {
    fontSize: 11,
    color: '#475569',
    lineHeight: 1.4
  },
  quoteContainer: {
    marginTop: 30,
    padding: 15,
    backgroundColor: '#eff6ff',
    borderRadius: 8
  },
  quote: {
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    color: '#1e40af'
  }
});

export const WorkoutPDF = ({ plan }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>AI Fitness Plan</Text>
      <Text style={styles.subHeader}>Generated tailored for you</Text>

      <Text style={styles.sectionTitle}>Workout Routine</Text>
      {plan.workout.map((ex, i) => (
        <View key={i} style={styles.itemContainer}>
          <Text style={styles.itemName}>{ex.exerciseName}</Text>
          <Text style={styles.itemDetails}>
            Sets: {ex.sets} • Reps: {ex.reps} • Rest: {ex.rest}
          </Text>
        </View>
      ))}

      <Text style={styles.sectionTitle}>Diet Plan</Text>
      {plan.diet.map((meal, i) => (
        <View key={i} style={styles.itemContainer}>
          <Text style={styles.itemName}>{meal.mealName}</Text>
          <Text style={styles.itemDetails}>
            {meal.foodItems}
          </Text>
          <Text style={{ fontSize: 10, color: '#166534', marginTop: 4 }}>
            ~ {meal.calories}
          </Text>
        </View>
      ))}

      <View style={styles.quoteContainer}>
        <Text style={styles.quote}>"{plan.motivation}"</Text>
      </View>

      <Text style={{ position: 'absolute', bottom: 30, left: 0, right: 0, textAlign: 'center', fontSize: 10, color: '#94a3b8' }}>
        Generated by FitAI Coach
      </Text>
    </Page>
  </Document>
);